# .github/workflows/release.yml
name: Release

# Tool name variable - change this to reuse the workflow for different tools
env:
  TOOL_NAME: "Callisto"

on:
  push:
    tags:
      - '*.*'
      - '*.*.*'

permissions:
  contents: write  # needed to publish releases and upload assets

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  macos-build:
    name: Build macOS
    runs-on: macos-15
    steps:
      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Git State
        run: |
          echo "=== Git Status ==="
          git status
          echo "=== Git Status Porcelain ==="
          git status --porcelain
          echo "=== Git Status Porcelain -uno ==="
          git status --porcelain -uno
          echo "=== Git Diff ==="
          git diff
          echo "=== Git Config ==="
          git config --list | grep -E "(core\.|user\.)"
          echo "=== Git Branch ==="
          git branch -a
          echo "=== Git Tags ==="
          git tag
          echo "=== Git Describe ==="
          git describe --tags --always

      - name: Debug Environment
        run: |
          echo "=== Environment Variables ==="
          env | grep -E "(CI|GITHUB|BUILD)" | sort
          echo "=== Current Directory ==="
          pwd
          echo "=== Directory Contents ==="
          ls -la

      - name: Resolve Packages
        run: |
          swift package resolve

      - name: Debug Before Build
        run: |
          echo "=== Git Status Before Build ==="
          git status --porcelain
          echo "=== Git Status Before Build (-uno) ==="
          git status --porcelain -uno

      - name: Debug PackageBuildInfo Script
        run: |
          echo "=== Testing PackageBuildInfo Script ==="
          find .build -name "packageBuildInfo.sh" -exec echo "Found: {}" \;
          find .build -name "packageBuildInfo.sh" -exec sh -c 'echo "Running: $1"; "$1" "$(pwd)" /tmp/test_output.swift myModule' _ {} \;
          echo "=== Generated Output ==="
          cat /tmp/test_output.swift

      - name: Build arm64
        run: |
          swift build -c release --arch arm64

      - name: Build x86_64
        run: |
          swift build -c release --arch x86_64

      - name: Debug Generated PackageBuildInfo
        run: |
          echo "=== Generated PackageBuild.swift Files ==="
          find .build -name "PackageBuild.swift" -exec echo "Found: {}" \;
          echo "=== Content of Generated Files ==="
          find .build -name "PackageBuild.swift" -exec sh -c 'echo "=== File: $1 ==="; cat "$1"' _ {} \;

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-debug
          path: .build/
          retention-days: 7
          include-hidden-files: true

      - name: Merge universal binary
        run: |
          lipo -create -output .build/release/${{ env.TOOL_NAME }} \
            .build/arm64-apple-macosx/release/${{ env.TOOL_NAME }} \
            .build/x86_64-apple-macosx/release/${{ env.TOOL_NAME }}

      - name: Check architecture
        run: lipo -info .build/release/${{ env.TOOL_NAME }}

      - name: Run ${{ env.TOOL_NAME }}
        run: .build/release/${{ env.TOOL_NAME }} --version

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TOOL_NAME }}-macOS
          path: .build/release/${{ env.TOOL_NAME }}

  create-release:
    name: Create GitHub Release
    needs: [macos-build]
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TOOL_NAME }}-macOS
          path: downloads/${{ env.TOOL_NAME }}-macOS

      - name: Make binaries executable
        run: | 
          chmod +x downloads/${{ env.TOOL_NAME }}-macOS/${{ env.TOOL_NAME }}

      - name: List Downloads
        run: ls -R downloads

      - name: Package Binaries
        run: |
          mkdir -p artifacts
          zip -j artifacts/${{ env.TOOL_NAME }}-macOS.zip downloads/${{ env.TOOL_NAME }}-macOS/${{ env.TOOL_NAME }}

      - name: List artifacts
        run: ls -R artifacts

      - name: Create Release & Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            artifacts/${{ env.TOOL_NAME }}-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
