# .github/workflows/release.yml
name: Release

# Tool name variable - change this to reuse the workflow for different tools
env:
  TOOL_NAME: "Callisto"
  CI: true

on:
  push:
    tags:
      - '*.*'
      - '*.*.*'

permissions:
  contents: write  # needed to publish releases and upload assets

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  macos-build:
    name: Build macOS
    runs-on: macos-15
    steps:
      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Resolve Packages
        run: |
          swift package resolve

      - name: Build arm64
        run: |
          swift build -c release --arch arm64

      - name: Verify arm64
        run: .build/arm64-apple-macosx/release/${{ env.TOOL_NAME }} --version

      - name: Build x86_64
        run: |
          swift build -c release --arch x86_64

      - name: Verify x86_64
        run: .build/x86_64-apple-macosx/release/${{ env.TOOL_NAME }} --version

      - name: Merge universal binary
        run: |
          rm .build/release
          mkdir .build/release
          lipo -create -output .build/release/${{ env.TOOL_NAME }} \
            .build/arm64-apple-macosx/release/${{ env.TOOL_NAME }} \
            .build/x86_64-apple-macosx/release/${{ env.TOOL_NAME }}

      - name: Check architecture
        run: lipo -info .build/release/${{ env.TOOL_NAME }}

      - name: Run ${{ env.TOOL_NAME }}
        run: .build/release/${{ env.TOOL_NAME }} --version

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TOOL_NAME }}-macOS
          path: .build/release/${{ env.TOOL_NAME }}

  create-release:
    name: Create GitHub Release
    needs: [macos-build]
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TOOL_NAME }}-macOS
          path: downloads/${{ env.TOOL_NAME }}-macOS

      - name: Make binaries executable
        run: | 
          chmod +x downloads/${{ env.TOOL_NAME }}-macOS/${{ env.TOOL_NAME }}

      - name: List Downloads
        run: ls -R downloads

      - name: Package Binaries
        run: |
          mkdir -p artifacts
          zip -j artifacts/${{ env.TOOL_NAME }}-macOS.zip downloads/${{ env.TOOL_NAME }}-macOS/${{ env.TOOL_NAME }}

      - name: List artifacts
        run: ls -R artifacts

      - name: Create Release & Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            artifacts/${{ env.TOOL_NAME }}-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
